version: "3.3"

services:

  app:
    container_name: app
    image: app
    build: .
    hostname: app
    env_file:
      - .env
    ports:
      - 8090:8080
    depends_on:
      - database
    restart: unless-stopped

  database:
    container_name: database
    image: mariadb:10.7.3
    hostname: database
    env_file:
      - .env
    ports:
      - 3308:3306
    restart: unless-stopped
